In [6]:
import torch

a = torch.tensor([10, 9, 8, 7])
a[1:3]

tensor([9, 8])

In [7]:
u = torch.tensor([1, 2])
v = torch.tensor([0, 1])

torch.dot(u, v)



tensor(2)

In [10]:
a = torch.tensor([[1, 3, 4], [3, 4, 6]])

print (a.size() , a.ndimension())

torch.Size([2, 3]) 2


In [16]:
import pandas as pd
df = pd.DataFrame({'A':[11, 33, 22],'B':[3, 3, 2]})

a = torch.tensor(df.values)
a

tensor([[11,  3],
        [33,  3],
        [22,  2]])

In [18]:
  X = torch.tensor([[1, 0], [0, 1]])
  Y = torch.tensor([[2, 1], [1, 2]]) 
  X_times_Y = X * Y

  X_times_Y

tensor([[2, 0],
        [0, 2]])