In [6]:
import torch

a = torch.tensor([10, 9, 8, 7])
a[1:3]

tensor([9, 8])

In [7]:
u = torch.tensor([1, 2])
v = torch.tensor([0, 1])

torch.dot(u, v)



tensor(2)

In [10]:
a = torch.tensor([[1, 3, 4], [3, 4, 6]])

print (a.size() , a.ndimension())

torch.Size([2, 3]) 2


In [16]:
import pandas as pd
df = pd.DataFrame({'A':[11, 33, 22],'B':[3, 3, 2]})

a = torch.tensor(df.values)
a

tensor([[11,  3],
        [33,  3],
        [22,  2]])

In [18]:
  X = torch.tensor([[1, 0], [0, 1]])
  Y = torch.tensor([[2, 1], [1, 2]]) 
  X_times_Y = X * Y

  X_times_Y

tensor([[2, 0],
        [0, 2]])

## 🔹 2️⃣ Matrix Multiplication (Linear Algebra Product)

For the **matrix product**,  
each element $(i, j)$ of the result is the **dot product** of the *i-th row* of $A$ and the *j-th column* of $B$.

---

### 🔸 Formula

$$
C = A \times B, \quad
c_{ij} = \sum_{k=1}^{n} a_{ik} b_{kj}
$$

where $n$ = number of columns in $A$ (or rows in $B$).

---

### 🔸 Step-by-Step with Positions

Let:

$$
A =
\begin{bmatrix}
2 & 3 \\
4 & 5
\end{bmatrix},
\quad
B =
\begin{bmatrix}
6 & 7 \\
8 & 9
\end{bmatrix}
$$

---

### ➤ For position **(0, 0)**

We take the **1st row** of $A$ and the **1st column** of $B$:

$$
A =
\begin{bmatrix}
\color{red}{2} & \color{red}{3} \\
4 & 5
\end{bmatrix},
\quad
B =
\begin{bmatrix}
\color{red}{6} & 7 \\
\color{red}{8} & 9
\end{bmatrix}
$$

Compute:
$$
(0,0): \; (2 \times 6) + (3 \times 8) = 46
$$

---

### ➤ For position **(0, 1)**

Take the **1st row** of $A$ and the **2nd column** of $B$:

$$
A =
\begin{bmatrix}
\color{red}{2} & \color{red}{3} \\
4 & 5
\end{bmatrix},
\quad
B =
\begin{bmatrix}
6 & \color{red}{7} \\
8 & \color{red}{9}
\end{bmatrix}
$$

Compute:
$$
(0,1): \; (2 \times 7) + (3 \times 9) = 51
$$

---

### ➤ For position **(1, 0)**

Take the **2nd row** of $A$ and the **1st column** of $B$:

$$
A =
\begin{bmatrix}
2 & 3 \\
\color{red}{4} & \color{red}{5}
\end{bmatrix},
\quad
B =
\begin{bmatrix}
\color{red}{6} & 7 \\
\color{red}{8} & 9
\end{bmatrix}
$$

Compute:
$$
(1,0): \; (4 \times 6) + (5 \times 8) = 68
$$

---

### ➤ For position **(1, 1)**

Take the **2nd row** of $A$ and the **2nd column** of $B$:

$$
A =
\begin{bmatrix}
2 & 3 \\
\color{red}{4} & \color{red}{5}
\end{bmatrix},
\quad
B =
\begin{bmatrix}
6 & \color{red}{7} \\
8 & \color{red}{9}
\end{bmatrix}
$$

Compute:
$$
(1,1): \; (4 \times 7) + (5 \times 9) = 75
$$

---

### ✅ Final Matrix Multiplication Result

$$
A \times B =
\begin{bmatrix}
46 & 51 \\
68 & 75
\end{bmatrix}
$$

---

📌 **Summary:**  
Each cell $(i, j)$ of the resulting matrix is obtained by **multiplying the i-th row of A**  
with the **j-th column of B** and summing the products.
