<a href="https://colab.research.google.com/github/prsundaram/python-series/blob/main/Simple_RNN/embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Word Embeddings using Keras

This notebook demonstrates how text is converted into numerical form and then into dense vector representations (embeddings).

Pipeline:

$$
\text{Text} \rightarrow \text{One Hot Encoding} \rightarrow \text{Padding} \rightarrow \text{Embedding Layer}
$$

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

## Step 1: Define Sentences

We start with a small corpus of sentences.

Let the dataset be:

$$
S = \{s_1, s_2, ..., s_n\}
$$

In [2]:
## sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'Understand the meaning of words',
    'your videos are good'
]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understand the meaning of words',
 'your videos are good']

## Step 2: Vocabulary Size

We define the vocabulary size for hashing.

Each word is mapped to an integer:

$$
\text{word} \rightarrow \text{index} \in [0, V)
$$

Where $V$ is the vocabulary size.

In [3]:
## Define the vocabulary size
voc_size = 10000

## Step 3: One Hot Representation

Each sentence is converted into a list of integers using hashing:

$$
\text{Sentence} \rightarrow [w_1, w_2, ..., w_k]
$$

Note: This is **not true one-hot encoding**, but a hashed representation.

In [4]:
### One Hot Representation
one_hot_rep = [one_hot(words, voc_size) for words in sent]
print(one_hot_rep)

[[1524, 8886, 8550, 2965], [1524, 8886, 8550, 2023], [1524, 4731, 8550, 5519], [685, 2909, 3381, 6002, 7061], [685, 2909, 3381, 6002, 5375], [9988, 1524, 4338, 8550, 5627], [6058, 7435, 2537, 6002]]


## Step 4: Padding Sequences

Neural networks require inputs of equal length.

We pad sequences to a fixed length:

$$
\text{length} = L
$$

Shorter sequences are padded with zeros.

In [9]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [12]:
sent_length = 8

embedded_docs = pad_sequences(
    one_hot_rep,
    padding='pre',
    maxlen=sent_length)

print(embedded_docs)

[[   0    0    0    0 1524 8886 8550 2965]
 [   0    0    0    0 1524 8886 8550 2023]
 [   0    0    0    0 1524 4731 8550 5519]
 [   0    0    0  685 2909 3381 6002 7061]
 [   0    0    0  685 2909 3381 6002 5375]
 [   0    0    0 9988 1524 4338 8550 5627]
 [   0    0    0    0 6058 7435 2537 6002]]


## Step 5: Embedding Layer

The embedding layer maps each word index to a dense vector:

$$
\text{Embedding}(i) = \vec{v}_i \in \mathbb{R}^d
$$

Where:
- $i$ → word index  
- $d$ → embedding dimension

In [13]:
## Feature representation
dim = 10

In [16]:
model = Sequential()
model.add(
    Embedding(
        voc_size,
        dim
    )
)

model.compile(
    'adam',
    'mse'
)

## Model Summary

The embedding matrix has shape:

$$
(V, d)
$$

Where:
- $V$ = vocabulary size  
- $d$ = embedding dimension

In [17]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

## Step 6: Generate Embeddings

Each input sequence is transformed into:

$$
(L, d)
$$

Where:
- $L$ = sentence length  
- $d$ = embedding dimension

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 984ms/step


array([[[-0.02647614,  0.01717992, -0.04891637, -0.01798369,
         -0.02259997,  0.02419206,  0.00465205,  0.04442577,
         -0.04730061,  0.0182732 ],
        [-0.02647614,  0.01717992, -0.04891637, -0.01798369,
         -0.02259997,  0.02419206,  0.00465205,  0.04442577,
         -0.04730061,  0.0182732 ],
        [-0.02647614,  0.01717992, -0.04891637, -0.01798369,
         -0.02259997,  0.02419206,  0.00465205,  0.04442577,
         -0.04730061,  0.0182732 ],
        [-0.02647614,  0.01717992, -0.04891637, -0.01798369,
         -0.02259997,  0.02419206,  0.00465205,  0.04442577,
         -0.04730061,  0.0182732 ],
        [ 0.01935   , -0.0026627 ,  0.0349267 ,  0.04583701,
          0.03881487,  0.00223098, -0.00840431,  0.02373991,
          0.00488503, -0.03210374],
        [-0.0255787 , -0.01885263, -0.0323478 ,  0.00292342,
         -0.0461003 , -0.02179861, -0.01995276,  0.04890898,
         -0.03123425,  0.02782318],
        [ 0.0359014 ,  0.00173677,  0.03219135,  0.0

## Inspect a Single Input

We check one padded sentence:

$$
\text{Input} \rightarrow [x_1, x_2, ..., x_L]
$$

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 1524, 8886, 8550, 2965], dtype=int32)

## Embedding for Single Sentence

The output becomes:

$$
(L, d) = (8, 10)
$$

Each word is now represented as a dense vector.

In [23]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[[-0.02647614,  0.01717992, -0.04891637, -0.01798369,
         -0.02259997,  0.02419206,  0.00465205,  0.04442577,
         -0.04730061,  0.0182732 ],
        [-0.02647614,  0.01717992, -0.04891637, -0.01798369,
         -0.02259997,  0.02419206,  0.00465205,  0.04442577,
         -0.04730061,  0.0182732 ],
        [-0.02647614,  0.01717992, -0.04891637, -0.01798369,
         -0.02259997,  0.02419206,  0.00465205,  0.04442577,
         -0.04730061,  0.0182732 ],
        [-0.02647614,  0.01717992, -0.04891637, -0.01798369,
         -0.02259997,  0.02419206,  0.00465205,  0.04442577,
         -0.04730061,  0.0182732 ],
        [ 0.01935   , -0.0026627 ,  0.0349267 ,  0.04583701,
          0.03881487,  0.00223098, -0.00840431,  0.02373991,
          0.00488503, -0.03210374],
        [-0.0255787 , -0.01885263, -0.0323478 ,  0.00292342,
         -0.0461003 , -0.02179861, -0.01995276,  0.04890898,
         -0.03123425,  0.02782318],
        [ 0.0359014 ,  0.00173677,  0.03219135,  0.0