# NumPy

NumPy (Numerical Python) is a **fundamental library for scientific computing** in Python.  
It provides:

- **Multi-dimensional arrays (ndarray)** → fast, efficient, and more powerful than Python lists.  
- **Mathematical functions** → element-wise operations, linear algebra, statistics, Fourier transforms, etc.  
- **Broadcasting** → perform arithmetic between arrays of different shapes.  
- **Memory efficiency** → stores data in contiguous blocks, enabling vectorized operations in C (much faster than Python loops).  
- **Integration** → works seamlessly with libraries like Pandas, SciPy, Scikit-learn, TensorFlow, and PyTorch.  

---

## Key Features of NumPy
1. **Ndarray object** → homogeneous multi-dimensional array.  
2. **Vectorization** → removes the need for slow Python loops.  
3. **Broadcasting** → automatic expansion of arrays during arithmetic.  
4. **Universal functions (ufuncs)** → fast element-wise mathematical operations.  
5. **Linear Algebra Support** → dot products, eigenvalues, matrix decompositions.  
6. **Random module** → random sampling, distributions, shuffling.  

---

## Example: Array Creation and Operations
```python
import numpy as np

# Create arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized operations (element-wise)
print("a + b =", a + b)    # [5 7 9]
print("a * b =", a * b)    # [ 4 10 18]

# Broadcasting
c = np.array([10])
print("a + c =", a + c)    # [11 12 13]

# Useful attributes
print("Shape:", a.shape)   # (3,)
print("Data type:", a.dtype)  # int64


In [52]:
# Intalling numpy from Jupyter notebook
!pip install numpy

In [53]:
import numpy as np

In [54]:
## Creating array using numpy
## Create 1D array 

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(f"Shape of the array is {arr1.shape}") # Output (5,) which means 1 D array

[1 2 3 4 5]
<class 'numpy.ndarray'>
Shape of the array is (5,)


In [55]:
arr2 = np.array([1, 2, 3, 4, 5])  

# arr2 is a 1D array with shape (5,)
print("Original:", arr2, "Shape:", arr2.shape)

arr2_row = arr2.reshape(1, 5)  
# .reshape(1, 5) → reshapes into 2D array
#  -> 1 row, 5 columns (row vector form)

print("Reshaped:", arr2_row, "Shape:", arr2_row.shape)

Original: [1 2 3 4 5] Shape: (5,)
Reshaped: [[1 2 3 4 5]] Shape: (1, 5)


In [56]:
# 1D Array
arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [57]:
# np.arange(start, stop, step)
# -> creates an array starting from 0 up to (but not including) 10
# -> with step size of 2
# So result = [0, 2, 4, 6, 8]
arr4 = np.arange(0, 10, 2)
print(arr4)

[0 2 4 6 8]


In [58]:
arr5 = np.arange(0, 10, 2).reshape(5, 1)  

# Step 1: np.arange(0, 10, 2)
#   → Creates array: [0, 2, 4, 6, 8]

# Step 2: .reshape(5, 1)
#   → Reshapes the 1D array of 5 elements into a 2D array
#   → 5 rows, 1 column

print(arr5)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [59]:
import numpy as np

arr = np.ones([3, 4])  

# np.ones([rows, cols])
# -> Creates a 2D array filled with 1s
# -> Shape here = (3,4) → 3 rows, 4 columns
# So result =
# [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]]

print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


✅ When this is useful:
- Initializing weights in machine learning before training (common before applying random initialization).
- Creating masks/matrices filled with 1s for operations.
- Quick placeholder arrays for testing or benchmarking.
- Element-wise multiplication/division where identity (1) makes sense.

In [60]:
arr_zeros = np.zeros((2, 3))  

# np.zeros((rows, cols))
# -> Creates a 2D array filled with 0s
# Shape = (2,3) → 2 rows, 3 columns
# Useful for initializing empty arrays where 0 is a natural placeholder.

print("np.zeros:\n", arr_zeros)

np.zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


✅ Use case:
- Initialize arrays before filling with computed values.
- Represent absence of data or default state.
- Often used in ML for starting weights/bias = 0.

In [61]:
arr_full = np.full((2, 3), 7)  

# np.full((rows, cols), value)
# -> Creates a 2D array filled with the given value (here, 7)
# Useful when you need constant initialization other than 0 or 1.

print("np.full:\n", arr_full)

np.full:
 [[7 7 7]
 [7 7 7]]


✅ Use case:
- Masking arrays with a default value (e.g., -1 for missing data).
- Initializing matrices with a constant starting weight.
- Quick testing with fixed values.

📝 Summary
- `np.zeros((shape))` → all elements 0.
- `np.ones((shape))` → all elements 1.
- `np.full((shape), value)` → all elements = value.

## Identity Matrix

An **Identity Matrix** is a square matrix with ones on the main diagonal and zeros elsewhere.  
It is denoted as \( I_n \) for an \( n \times n \) matrix:

$$
I_n =
\begin{bmatrix}
1 & 0 & 0 & \cdots & 0 \\
0 & 1 & 0 & \cdots & 0 \\
0 & 0 & 1 & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & 1
\end{bmatrix}
$$

**Property**: Multiplying any \( n \times n \) matrix \( A \) with the identity matrix \( I_n \) gives back \( A \):

$$
A \times I_n = I_n \times A = A
$$


In [62]:
# Method 1: np.eye()
I1 = np.eye(3)  
# Creates a 3x3 identity matrix
# np.eye(N, M=None, k=0)
#   N = rows
#   M = cols (default = N, so square matrix)
#   k = index of diagonal (0 = main, +1 = above, -1 = below)

print("np.eye(3):\n", I1)


# Method 2: np.identity()
I2 = np.identity(4)  
# Creates a 4x4 identity matrix
# Shortcut for np.eye(N)

print("np.identity(4):\n", I2)


np.eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
np.identity(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Understanding NumPy Array Attributes

Consider the array:

$$
arr6 =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

- **Shape**: \((2, 3)\)  
  - 2 rows, 3 columns.  
- **Number of Dimensions (`ndim`)**: \(2\)  
  - This is a 2D array (matrix).  
- **Size (`size`)**: \(2 \times 3 = 6\)  
  - Total number of elements.  
- **Data type (`dtype`)**: typically `int64` (depends on system).  
- **Item size (`itemsize`)**: number of bytes used per element.  
  - Example: for `int64`, each element uses \(8\) bytes.

---

### Visual Representation

- **Shape (2,3)**:
  $$
  \underbrace{[1 \; 2 \; 3]}_{\text{Row 1}}, \quad
  \underbrace{[4 \; 5 \; 6]}_{\text{Row 2}}
  $$

- **ndim = 2** → rows & columns.  
- **size = 6** → all elements counted:  
  $$
  1, 2, 3, 4, 5, 6
  $$


In [63]:
# Create a 2D NumPy array with 2 rows and 3 columns
arr6 = np.array([[1, 2, 3], [4, 5, 6]])

# Display the full array
print(f"Array:\n{arr6}")

# Shape → returns a tuple (rows, columns)
# In this case, arr6 has 2 rows and 3 columns → (2, 3)
print(f"Shape: {arr6.shape}")  # (2, 3)

# Number of dimensions (ndim) → how many axes the array has
# 1D → vector, 2D → matrix, 3D → tensor
# Here arr6 is a matrix → ndim = 2
print(f"Number of dimensions: {arr6.ndim}")

# Size → total number of elements in the array
# Formula = product of shape = rows × columns
# Here: 2 × 3 = 6
print(f"Size (number of elements): {arr6.size}")

# Data type (dtype) → the type of each element
# NumPy infers type automatically (int64 by default on most systems for integers)
print(f"Data type: {arr6.dtype}")

# Item size (itemsize) → memory (in bytes) taken by one element
# Example: int64 → 8 bytes, float32 → 4 bytes
# This helps estimate memory usage for large arrays
print(f"Item size (in bytes): {arr6.itemsize}")

Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


## NumPy Array Attributes (Quick Reference)

| Attribute    | Description                                                                 | Example (for $arr6 = [[1, 2, 3], [4, 5, 6]]$) |
|--------------|-----------------------------------------------------------------------------|-----------------------------------------------|
| `shape`      | Tuple representing dimensions (rows, columns, …).                           | $(2, 3)$ → 2 rows, 3 columns                  |
| `ndim`       | Number of dimensions (axes).                                                | $2$ → 2D array (matrix)                       |
| `size`       | Total number of elements.                                                   | $2 \times 3 = 6$                              |
| `dtype`      | Data type of elements.                                                      | `int64` (platform-dependent)                  |
| `itemsize`   | Memory (in bytes) used by each element.                                     | $8 \; \text{bytes per element (for int64)}$   |

---

### Visual Example (Matrix Form)

$$
arr6 =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

- **Shape** = $(2,3)$  
- **ndim** = $2$  
- **size** = $6$  
- **dtype** = `int64`  
- **itemsize** = $8$ bytes  


# NumPy Vectorized Operations

NumPy supports **vectorization**, meaning operations are applied **element-wise** without explicit loops.  
This makes code **faster** and **more concise**.

Given two arrays:

$$
array_1 = [1, 2, 3, 4, 5], \quad array_2 = [10, 20, 30, 40, 50]
$$

---

## 1. Addition
$$
array_1 + array_2 = [1+10,\; 2+20,\; 3+30,\; 4+40,\; 5+50]
$$

---

## 2. Subtraction
$$
array_1 - array_2 = [1-10,\; 2-20,\; 3-30,\; 4-40,\; 5-50]
$$

---

## 3. Multiplication
$$
array_1 \times array_2 = [1 \times 10,\; 2 \times 20,\; 3 \times 30,\; 4 \times 40,\; 5 \times 50]
$$

---

## 4. Division
$$
\frac{array_1}{array_2} =
\left[\frac{1}{10},\; \frac{2}{20},\; \frac{3}{30},\; \frac{4}{40},\; \frac{5}{50}\right]
$$

---

## 5. Power
$$
array_1^{\,2} = [1^2,\; 2^2,\; 3^2,\; 4^2,\; 5^2]
$$

---

## 6. Square Root
$$
\sqrt{array_2} = [\sqrt{10},\; \sqrt{20},\; \sqrt{30},\; \sqrt{40},\; \sqrt{50}]
$$

---

## 7. Dot Product (Linear Algebra)
$$
array_1 \cdot array_2 = 1\cdot10 + 2\cdot20 + 3\cdot30 + 4\cdot40 + 5\cdot50
$$

---

## 8. Comparison (Element-wise)
$$
array_1 > array_2 = [1>10,\; 2>20,\; 3>30,\; 4>40,\; 5>50] = [False, False, False, False, False]
$$

$$
array_1 < array_2 = [1<10,\; 2<20,\; 3<30,\; 4<40,\; 5<50] = [True, True, True, True, True]
$$

$$
array_1 == array_2 = [1=10,\; 2=20,\; 3=30,\; 4=40,\; 5=50] = [False, False, False, False, False]
$$

---

## 9. Aggregate Operations
- Sum: 
$$
\text{sum}(array_1) = 1+2+3+4+5 = 15
$$

- Mean: 
$$
\text{mean}(array_2) = \frac{10+20+30+40+50}{5} = 30
$$

- Max: 
$$
\max(array_2) = 50
$$

- Min: 
$$
\min(array_1) = 1
$$

- Standard Deviation: 
$$
\sigma(array_1) = \sqrt{\frac{\sum (x_i - \mu)^2}{n}}
$$

---

## 10. Transpose
If  
$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$  

Then:  
$$
A^T =
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
$$

---

## 11. Matrix Multiplication
$$
A @ B
$$
represents matrix multiplication (not element-wise).  

---

## 12. Determinant & Inverse (Linear Algebra)
For a square matrix \( A \):  
- Determinant:  
$$
|A|
$$
- Inverse:  
$$
A^{-1}
$$

---

## 13. Logical Operations
- Logical AND:  
$$
\text{logical\_and}(array_1 > 2,\; array_2 < 40)
$$  

- Logical OR:  
$$
\text{logical\_or}(array_1 < 3,\; array_2 > 20)
$$  

- Logical NOT:  
$$
\text{logical\_not}(array_1 > 3)
$$  

---

## 14. Broadcasting
Broadcasting allows operations between arrays of different shapes.  

Example:  
$$
[1, 2, 3, 4, 5] + 10 = [11, 12, 13, 14, 15]
$$  

Another example:  
$$
\begin{bmatrix}1 \\ 2 \\ 3\end{bmatrix} +
\begin{bmatrix}10 & 20 & 30\end{bmatrix}
=
\begin{bmatrix}
11 & 21 & 31 \\
12 & 22 & 32 \\
13 & 23 & 33
\end{bmatrix}
$$


In [64]:
# ---------------------------------------------------------------------
# Setup: two 1-D arrays (same shape) and a small 2-D matrix for linear algebra
# ---------------------------------------------------------------------
array_1 = np.array([1, 2, 3, 4, 5])               # shape (5,)
array_2 = np.array([10, 20, 30, 40, 50])          # shape (5,)

# Small 2x3 matrix for transpose etc. (non-square)
A = np.array([[1, 2, 3],
              [4, 5, 6]])                         # shape (2,3)

# Square matrix for determinant / inverse / matrix multiplication
M = np.array([[1.0, 2.0],
              [3.0, 4.0]])                        # shape (2,2) - float for inverse

print("=== Input arrays ===")
print("array_1:", array_1)
print("array_2:", array_2)
print("A:\n", A)
print("M:\n", M)
print()

# ---------------------------------------------------------------------
# 1) Basic arithmetic (element-wise) - fastest and most common
# ---------------------------------------------------------------------
print("=== Element-wise arithmetic ===")
print("Addition (array_1 + array_2):", array_1 + array_2)   # element-wise add
print("Subtraction (array_1 - array_2):", array_1 - array_2) # element-wise subtract
print("Multiplication (array_1 * array_2):", array_1 * array_2) # element-wise multiply
print("Division (array_1 / array_2):", array_1 / array_2)   # element-wise float division
print("Floor division (array_2 // array_1):", array_2 // array_1) # element-wise floor div
print("Modulus (array_2 % array_1):", array_2 % array_1)   # element-wise remainder
print("Power (array_1 ** 2):", array_1 ** 2)               # element-wise power
print("Square root (np.sqrt(array_2)):", np.sqrt(array_2)) # element-wise sqrt
print()

# ---------------------------------------------------------------------
# 2) Universal functions (ufuncs) - explicit C-backed ops
# ---------------------------------------------------------------------
print("=== Universal functions (ufuncs) ===")
print("np.add(array_1, array_2):", np.add(array_1, array_2))     # same as + but function form
print("np.multiply(array_1, array_2):", np.multiply(array_1, array_2))
print("np.power(array_1, 3):", np.power(array_1, 3))             # cube each element
print()

# ---------------------------------------------------------------------
# 3) Comparison (element-wise) -> returns boolean array
# ---------------------------------------------------------------------
print("=== Comparison (element-wise) ===")
print("array_1 > array_2:", array_1 > array_2)   # element-wise comparison -> boolean array
print("array_1 < array_2:", array_1 < array_2)
print("array_1 == array_1:", array_1 == array_1) # element-wise equality
print()

# ---------------------------------------------------------------------
# 4) Logical operations (combine boolean masks)
# ---------------------------------------------------------------------
print("=== Logical operations ===")
mask_gt_2 = array_1 > 2                         # boolean mask for elements > 2
mask_lt_40 = array_2 < 40                       # boolean mask for corresponding array_2 elements
print("mask_gt_2:", mask_gt_2)
print("mask_lt_40:", mask_lt_40)
print("logical_and(mask_gt_2, mask_lt_40):", np.logical_and(mask_gt_2, mask_lt_40))
print("logical_or(mask_gt_2, mask_lt_40):", np.logical_or(mask_gt_2, mask_lt_40))
print("logical_not(mask_gt_2):", np.logical_not(mask_gt_2))
print()

# ---------------------------------------------------------------------
# 5) Aggregates (reduce operations) - global or axis-wise
# ---------------------------------------------------------------------
print("=== Aggregate operations ===")
print("sum(array_1):", np.sum(array_1))
print("mean(array_2):", np.mean(array_2))
print("max(array_2):", np.max(array_2))
print("min(array_1):", np.min(array_1))
print("std(array_1):", np.std(array_1))          # population std dev
# Aggregate along an axis for 2D array A
print("sum over rows (axis=1) for A:", np.sum(A, axis=1))   # sums for each row
print("sum over cols (axis=0) for A:", np.sum(A, axis=0))   # sums for each column
print()

# ---------------------------------------------------------------------
# 6) Linear algebra (dot, matmul, transpose, det, inv)
# ---------------------------------------------------------------------
print("=== Linear algebra ===")
# Dot product (1-D arrays) -> scalar
print("Dot product (array_1 . array_2):", np.dot(array_1, array_2))

# Matrix multiplication: use @ or np.matmul
# To multiply A (2x3) with B (3x2) we'd need compatible shapes; demonstrate transpose to multiply A^T @ A if needed.
print("A^T (transpose):\n", A.T)
# Example: compute M @ M (matrix multiplication) and np.matmul
print("Matrix multiplication M @ M:\n", M @ M)
print("np.matmul(M, M):\n", np.matmul(M, M))

# Determinant and inverse (only valid for square matrices)
det_M = np.linalg.det(M)
print("det(M):", det_M)
if abs(det_M) > 1e-12:
    inv_M = np.linalg.inv(M)
    print("inv(M):\n", inv_M)
else:
    print("M is singular (non-invertible), cannot compute inverse.")
print()

# ---------------------------------------------------------------------
# 7) Broadcasting - operate between different shapes (no data copy)
# ---------------------------------------------------------------------
print("=== Broadcasting ===")
# Scalar broadcast: scalar expands to array shape
print("array_1 + 10:", array_1 + 10)

# 1D + 2D broadcasting example:
col = np.array([[1], [2], [3]])   # shape (3,1)
row = np.array([10, 20, 30, 40])  # shape (4,)
# To make a clear broadcasting example, create compatible sizes:
B_col = np.array([[1], [2], [3]])           # (3,1)
B_row = np.array([10, 20, 30])              # (3,) -> can broadcast to (3,3)
print("B_col (3x1):\n", B_col)
print("B_row (3,):", B_row)
print("Broadcasted sum B_col + B_row -> shape", (B_col + B_row).shape)
print("B_col + B_row:\n", B_col + B_row)    # each row adds the row vector
print()

# ---------------------------------------------------------------------
# 8) Useful helpers: where, clip, unique, argsort
# ---------------------------------------------------------------------
print("=== Useful helpers ===")
# where(condition, x, y) -> choose element-wise from x or y based on condition
print("np.where(array_1 % 2 == 0, array_1, -array_1):", np.where(array_1 % 2 == 0, array_1, -array_1))

# clip: bound values between min and max
vals = np.array([-5, -1, 0, 2, 10])
print("np.clip(vals, 0, 5):", np.clip(vals, 0, 5))

# unique: returns sorted unique elements
dup = np.array([1, 2, 2, 3, 1])
print("np.unique(dup):", np.unique(dup))

# argsort: indices that would sort the array
print("np.argsort(array_2):", np.argsort(array_2))
print()

# ---------------------------------------------------------------------
# 9) Type casting and memory notes
# ---------------------------------------------------------------------
print("=== Type casting and memory notes ===")
float_array = array_1.astype(np.float32)   # change dtype explicitly
print("array_1 dtype:", array_1.dtype, "-> float_array dtype:", float_array.dtype)
print("itemsize (bytes) for dtype int:", array_1.itemsize, "for float32:", float_array.itemsize)
print()

# ---------------------------------------------------------------------
# 10) Notes / caveats
# ---------------------------------------------------------------------
print("=== Notes / caveats ===")
print("- Operations are vectorized and performed in compiled code (C): very fast.")
print("- Make sure shapes align or broadcasting rules apply; otherwise NumPy raises a ValueError.")
print("- Be careful with division: dividing integers yields floats; dividing by zero gives inf or raises warnings.")
print("- For very large arrays consider memory usage (dtype and itemsize).")


=== Input arrays ===
array_1: [1 2 3 4 5]
array_2: [10 20 30 40 50]
A:
 [[1 2 3]
 [4 5 6]]
M:
 [[1. 2.]
 [3. 4.]]

=== Element-wise arithmetic ===
Addition (array_1 + array_2): [11 22 33 44 55]
Subtraction (array_1 - array_2): [ -9 -18 -27 -36 -45]
Multiplication (array_1 * array_2): [ 10  40  90 160 250]
Division (array_1 / array_2): [0.1 0.1 0.1 0.1 0.1]
Floor division (array_2 // array_1): [10 10 10 10 10]
Modulus (array_2 % array_1): [0 0 0 0 0]
Power (array_1 ** 2): [ 1  4  9 16 25]
Square root (np.sqrt(array_2)): [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]

=== Universal functions (ufuncs) ===
np.add(array_1, array_2): [11 22 33 44 55]
np.multiply(array_1, array_2): [ 10  40  90 160 250]
np.power(array_1, 3): [  1   8  27  64 125]

=== Comparison (element-wise) ===
array_1 > array_2: [False False False False False]
array_1 < array_2: [ True  True  True  True  True]
array_1 == array_1: [ True  True  True  True  True]

=== Logical operations ===
mask_gt_2: [False False